### ISSUE TITLE
ios xcode 14，14 Pro。打开布局边框之后出现崩溃。

### ISSUE THREAD

**Issue by YueLiXing** [didi/DoKit#1077]
It is recommended to refer to the following process before submitting issues：https://github.com/didi/DoraemonKit/issues/745
If you still cannot solve your problem, you can submit your issue according to the following template

Please complete the following informations.
> Android、iOS? OS version? Brand? 
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> More informations such as error messages and stack traces are welcomed.
>

建议提issues之前可以参考一下DoKit社区答疑流程：https://github.com/didi/DoraemonKit/issues/745
假如还是无法解决你的问题，你可以按照以下模板来提交你的issue

请补充如下信息。
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
**iOS 使用 xcode 14， 14 Pro 模拟器。打开布局边框之后直接崩溃**
> 期望的表现和实际的表现。（如有）
**期望点击能够正常使用,不要发生崩溃**
> 问题重现的步骤。（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

```
// 就是这个代码出的问题
UIWindow *statusBarWindow = [[UIApplication sharedApplication] valueForKey:@"_statusBarWindow"];
```

**Comment by gitzjp** [comment]
我也需要同样的问题

**Comment by gitzjp** [comment]
iOS16的手机和模拟器遇到了。
打开布局边框之后直接崩溃
期望的表现和实际的表现。
期望点击能够正常使用,不要发生崩溃
问题重现的步骤。
其他的错误信息和堆栈信息如果有也可以一并提供出来。
