### ISSUE TITLE
iOS 审核问题

### ISSUE THREAD

**Issue by 18911131970** [didi/DoKit#1093]
<img width="709" alt="WeChatWorkScreenshot_cfc06c8c-187c-4de9-b119-893fb6aed609" src="https://user-images.githubusercontent.com/12705578/199882931-f33c8b7c-bde5-48b9-9cc5-ac74b1ecc1b3.png">

**Comment by 18911131970** [comment]
close

**Comment by doubleJJJJ** [comment]
> ![image](https://user-images.githubusercontent.com/12705578/199882986-669456ed-3fbf-43d3-a664-303d93f51d9f.png)

我审核也遇到这个问题被拒了，请问你是怎么解决的？
